const BROWSE_FOLDER = 'BROWSE_FOLDER'
const FILEINFO_DELETE = 'FILEINFO_DELETE'
const FILEINFO_SAVE = 'FILEINFO_SAVE'
const FILEINFO_LIST = 'FILEINFO_LIST'
const COPY = 'COPY'
const GET_COPY = 'GET_COPY'
const COPY_CANCEL = 'COPY_CANCEL'

module.exports = {
    BROWSE_FOLDER,
    FILEINFO_DELETE,
    FILEINFO_SAVE,
    FILEINFO_LIST,
    COPY,
    GET_COPY,
    COPY_CANCEL,
}